name: github-trending

on:
  schedule:
  - cron: "30 23 * * *"
  workflow_dispatch:

jobs:
  github-trending:
    runs-on: ubuntu-latest
    steps:
      # Check out code using git
      - uses: actions/checkout@v2
      # Install Node 12
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: npm install
        run: npm install
        working-directory: .
      - name: fetch data
        run: node src/actions/github-trending.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
