name: v2ex-hot

on:
  schedule:
  - cron: "30 15 * * *"
  workflow_dispatch:

jobs:
  v2ex-hot:
    runs-on: ubuntu-latest
    steps:
      # Check out code using git
      - uses: actions/checkout@v2
      # Install Node 12
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: npm install
        run: npm install
        working-directory: .
      - name: fetch data
        run: node .github/actions/v2ex-hot.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
